Ft reset password web ui
BuildForSDG/farmrail pull request #40
Opened 2020-05-12 18:47 UTC by Faithaigo

## Description
Please include a summary of the change and relevant motivation and context. 
List any dependencies that are required for this change.

All pull requests should be related to open issues. Indicate the issue(s) bellow and remove this line:
Fixes #(issue number 1) #(issue number 2 if applicable)

## How Has This Been Tested?
Please describe in detail how you tested your changes.
Include details of your testing environment, and the tests you ran to see how your change affects other areas of the code etc.

## Screenshots (if applicable, else remove this line / section)

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added necessary inline code documentation
- [ ] I have added tests that prove my fix is effective and that this feature works
- [ ] New and existing unit tests pass locally with my changes

2020-05-12 21:59 UTC, amkayondo requested changes
Add tests for this component and also fix the needed changes

2020-05-12 21:59 UTC, amkayondo commented on src/web_ui/src/components/Forms/ResetPassword.js
> +                        <Input type="text"/>
add a placeholder for the input

2020-05-12 21:59 UTC, amkayondo commented on src/web_ui/src/components/Forms/ResetPassword.js
> +                    <Img src="/images/resetimg.jpg"></Img>
add an alternative text placeholder for the image 
also, place the image in an images folder like **src/assests/images/auth** for easy access by other components

2020-05-12 21:59 UTC, amkayondo commented on src/web_ui/src/components/Forms/ResetPassword.js
> +                    <Img src="/images/resetimg.jpg"></Img>
Also, it's a good practice to use **`<Img src="/images/resetimg.jpg" />`** than **`<Img src="/images/resetimg.jpg"></Img>`**  if the element does not surround any content like **<div>{ component }</div>**

2020-05-18 15:49 UTC, kmwamasali approved these changes
Changes approved

2020-05-18 16:00 UTC, merged