updating the read-me file
BuildForSDG/farmrail pull request #76
Opened 2020-06-04 13:19 UTC by swimking

## Description
Please include a summary of the change and relevant motivation and context. 
List any dependencies that are required for this change.

All pull requests should be related to open issues. Indicate the issue(s) bellow and remove this line:
Fixes #(issue number 1) #(issue number 2 if applicable)

## How Has This Been Tested?
Please describe in detail how you tested your changes.
Include details of your testing environment, and the tests you ran to see how your change affects other areas of the code etc.

## Screenshots (if applicable, else remove this line / section)

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added necessary inline code documentation
- [ ] I have added tests that prove my fix is effective and that this feature works
- [ ] New and existing unit tests pass locally with my changes

2020-06-04 18:20 UTC, LadPaule reviewed
is it okay to add the link to the netlify provisional space
https://farmrail-staging.netlify.app/

2020-06-05 17:32 UTC, amkayondo requested changes
reference the modifications with  https://medium.com/@meakaakka/a-beginners-guide-to-writing-a-kickass-readme-7ac01da88ab3

2020-06-05 17:32 UTC, amkayondo commented on README.md
>  Build for SDG project repo
Place this under the Title

2020-06-05 17:32 UTC, amkayondo commented on README.md
> +PRODUCT DESCRIPTION
bold this

2020-06-05 17:32 UTC, amkayondo commented on README.md
> +## Project Name: Farm Rail
make it bigger as it the header

2020-06-05 17:32 UTC, amkayondo commented on README.md
> + ## installation
Please reference to https://medium.com/@meakaakka/a-beginners-guide-to-writing-a-kickass-readme-7ac01da88ab3 for a better Read Me

2020-06-08 08:28 UTC, merged